conv: new internal command: DepsAny and CommandAny (help for python2 VS python3)

diff --git a/bin/conv b/bin/conv
--- a/bin/conv
+++ b/bin/conv
@@ -175,5 +175,23 @@ Deps() {
 	done
 	return 0
 }
+CommandAny() {
+	while [ $# -gt 0 ]; do
+		if command >/dev/null 2>&1 -v "$1"; then
+			command -v "$1"
+			return 0
+		fi
+		shift
+	done
+	return 1
+}
+DepsAny() {
+	local self="DepsAny"
+	if ! CommandAny "$@" >/dev/null; then
+		echo >&2 "ERROR: ${self}: missing dependency (command $*)"
+		return 1
+	fi
+
+}
 
 _conv "$@"
